### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by Pheno-menal** [SamRodrigue/mulbox#1]
- [ ]  Style header and mascot to "compact mode" when first textarea is highlighted or when 2nd textarea is rendered. (pug.js layout template?)

- [x] make text in textarea more legible 

- [ ] logic behind slider button (char limit and maybe different styles for imgur/twitter mode)

- [x] when textarea reaches border change to grid

- [ ] maybe(?) implement saving feature so text won't disappear on reload 
       ?cookies with full text that loads if populated?

- [ ] limit number of textareas and display a warning modal telling the user they reached the limit (would limit if we ever implement a saving feature)

- [x] style about modal with info on the project and GitHub link

- [ ] style for google ad banners(?)

- [ ] Consider licence 

- [x] Update readme

- [ ] add delete all button

- [ ] can use arrow keys to move cursor across mulboxes

Will add more when I think of them
